export const FETCH_COFFEE_ITEMS = 'FETCH_COFFEE_ITEMS';
export const FETCH_CART_ITEMS = 'FETCH_CART_ITEMS';
export const ADD_COFFEE_TO_CART = 'ADD_COFFEE_TO_CART';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const CART_CHECKOUT = 'CART_CHECKOUT';