export const FETCH_COFFEE_ITEMS = 'FETCH_COFFEE_ITEMS';
export const ADD_COFFEE_TO_CART = 'ADD_COFFEE_TO_CART';
export const ADD_COFFEE_TO_WISH = 'ADD_COFFEE_TO_WISH';

export const FETCH_CART_ITEMS = "FETCH_CART_ITEMS";
export const FETCH_WISH_ITEMS = "FETCH_WISH_ITEMS";
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const REMOVE_WISH_ITEM = 'REMOVE_WISH_ITEM';
export const CART_CHECKOUT = 'CART_CHECKOUT';
export const WISH_CHECKOUT = 'WISH_CHECKOUT';